spring.application.name=nexum-crm

# Configurando o Spring para ler o arquivo .env
spring.config.import=optional:file:.env[.properties]

# Conexão com o banco de dados via variáveis do .env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Manutenção de conexões ativas no Neon DB
spring.datasource.hikari.keepalive-time=30000

# Configurações do Flyway (controle de versão do banco)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Configurações do JPA / Hibernate
# Desabilitado DDL automático do Hibernate para não conflitar com as migrations do Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect