spring.application.name=nexum-crm

#Configurando o spring para achar o .env
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.docker.compose.enabled=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.datasource.hikari.keepalive-time=30000

#Configurações hibernates
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect